name: CI

on:
  pull_request:

env:
  GO_VER: '1.24.*'

jobs:
  test:
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: 
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VER }}

      - name: Test
        run: go test -v -bench=. -benchmem ./...

      - name: Build
        run: go build -v

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VER }}

      - name: Lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: latest
